spring.application.name=burgerManager
server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=your_name
spring.datasource.password = your_password
spring.jpa.hibernate.ddl-auto=create
logging.level.org.hibernate.SQL=debug 
logging.level.org.hibernate.jdbc.bind=trace 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
